### ISSUE TITLE
나중에 코드 합칠 때

### ISSUE THREAD

**Issue by ehyuu** [YerinJoo/SoftwareEngineering#3]
**_main 안에 있는 while문을 메뉴 함수로 따로 뺄까요 아님 그대로 둘까요_** ㅁㄴㅇㄻㅇㄹ

**Comment by SohhyangLee** [comment]
따로 뺀다는 게 어떤 말이죵

**Comment by SohhyangLee** [comment]
@ehyuu 빨리 알려주세요

**Comment by ehyuu** [comment]
@SohhyangLee 조용히하세요

**Comment by ehyuu** [comment]
메모장 계산기 가계부 선택하는 메뉴 돌리는 부분을 메소드로 만들까 하는 말이엇습니다 @SohhyangLee

**Comment by SohhyangLee** [comment]
그렇군요 잘 알겠습니다 그냥 메인에 다  넣읍시다

**Comment by ehyuu** [comment]
힝입니다 알겟습니다
