### ISSUE TITLE
왜 다 메뉴 while문으로 돌리시죠?

### ISSUE THREAD

**Issue by ehyuu** [YerinJoo/SoftwareEngineering#7]
전 do while이 더 좋습니다 따지는거 아닙니다 궁금한겁니다 **QUESTION**

**Comment by SohhyangLee** [comment]
if문으로 짜도 상관없지만 while문이 익숙해서 그랬습니다.

**Comment by ehyuu** [comment]
@SohhyangLee 알겠습니다 ㄳ합니다
