### ISSUE TITLE
코드 마감 기한

### ISSUE THREAD

**Issue by YerinJoo** [YerinJoo/SoftwareEngineering#8]
2차 제출일은 5일이고 3차에서 유닛테스트 진행할텐데 5일까지 완성 안되었을 때 코드 동작 확인 완료 언제까지 하는 게 좋을까요?

**Comment by ehyuu** [comment]
3차 제출 날짜가 언제죠

**Comment by SohhyangLee** [comment]
그래도 적어도 이번 주 주말까지는 완성해야 될 것 같습니다

**Comment by YerinJoo** [comment]
3차 12월 23일 입니다

**Comment by ehyuu** [comment]
이번주나 다음주까진 되어야 할 거 같습니다

**Comment by YerinJoo** [comment]
그렇다면 일단 10일까지로 생각해보겠습니다
